-- RoamSonio Editorial Library foundation
-- Safe foundation only: does not modify existing users, trips, families, or trip data.
-- Apply after the existing RoamSonio admin foundation migrations.

create table if not exists public.roamsonio_editorial_destinations (
  id text primary key,
  name text not null,
  type text not null check (type in ('City','Region','Ski & Snowboard','Outdoor','Coast & Island','Road Trip','Seasonal Experience')),
  category text not null,
  seasons text[] not null default '{}',
  buildable boolean not null default true,
  build_destination text,
  tagline text,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roamsonio_editorial_photos (
  id bigint generated by default as identity primary key,
  destination_id text not null references public.roamsonio_editorial_destinations(id) on delete cascade,
  url text not null,
  alt_text text not null default '',
  credit text not null default '',
  source_url text not null default '',
  role text not null default 'hero' check (role in ('hero','secondary','mobile')),
  sort_order integer not null default 0,
  approved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists roamsonio_editorial_destinations_status_idx
  on public.roamsonio_editorial_destinations(status, type, updated_at desc);
create index if not exists roamsonio_editorial_photos_destination_idx
  on public.roamsonio_editorial_photos(destination_id, approved, sort_order);

alter table public.roamsonio_editorial_destinations enable row level security;
alter table public.roamsonio_editorial_photos enable row level security;

drop policy if exists "published editorial destinations are public read" on public.roamsonio_editorial_destinations;
create policy "published editorial destinations are public read"
on public.roamsonio_editorial_destinations for select to anon, authenticated
using (status='published');

drop policy if exists "approved editorial photos are public read" on public.roamsonio_editorial_photos;
create policy "approved editorial photos are public read"
on public.roamsonio_editorial_photos for select to anon, authenticated
using (approved=true and exists (select 1 from public.roamsonio_editorial_destinations d where d.id=destination_id and d.status='published'));

-- Master Admin management is intentionally not exposed through direct browser writes.
-- The Master Account UI will use dedicated protected RPCs for create/edit/publish/photo approval.
-- Those RPCs will require Master Admin + AAL2 and will write admin audit events.

revoke all on public.roamsonio_editorial_destinations from anon, authenticated;
revoke all on public.roamsonio_editorial_photos from anon, authenticated;
grant select on public.roamsonio_editorial_destinations to anon, authenticated;
grant select on public.roamsonio_editorial_photos to anon, authenticated;
